### ISSUE TITLE
Need more example of using Graph version

### ISSUE THREAD

**Issue by nguyendacthienngan** [Icyrockton/MegaVul#2]
Hi, it's great to have a large precision dataset like MegaVul, but I want to use the graph version of your dataset (I did download the zip file). I don't know how to use next, can you kindly keep some examples of using it? I did see your 3 examples but don't understand much

**Comment by Icyrockton** [comment]
The graph is generated by Joern and exported in JSON format. Please refer to Joern's documentation for its specifications. You can play with the Joern CLI to understand the content of its graphs. 
You may also refer to vulnerability deep learning model like ivdetect to see how they use Joern graphs to generate features. 
e.g.
- [https://github.com/vulnerabilitydetection/VulnerabilityDetectionResearch/blob/new_implementation/IVDetect/scripts/joern_graphs.sc](url) 
- https://github.com/vinci-grape/SVulD/blob/master/Source_Code/IVDetect/dataset.py
- https://docs.joern.io/traversal-basics/
